pipeline {
    agent {
        label 'builder'
    }

    environment {
        //sonarqube_token = credentials('sonarqube-token')
        MAVEN_CREDENTIALS = credentials('nexus-creds-id')
    }
    
    tools {
        maven 'Maven'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('Build & Deploy') {
            steps {
                sh 'mvn clean deploy -DaltDeploymentRepository=releases::default::http://54.155.163.70:8081/repository/maven-releases/'
            }
        }
    }
       
}